name: Checkpoints
version: 1.0.5
main: me.duker02.parkour.Main
authors:
- DukerHD
description: Parkour checkpoints.

commands:
  checkpoint:
    description: Base command.
  cp:
    description: 'alias for checkpoint'